#---------------------------------------------------#
# EDP 380C.26: Simulation in R
# Lab 3: An Overview of Linear Regression 
#        and Data Generation
#
#' Discuss what this function does...
#'
#' @param n Describe this parameter here...
#' @param mu Describe this parameter here...
#' @param Sigma Describe this parameter here...
#' @return Describe what this returns...
rmvnorm <- function(n, mu, Sigma) {
	# Insert your implementation here...
}
